use_frameworks!

platform :ios, '9.0'

target 'objchttp_Example' do
  pod 'objchttp', :path => '../'

  target 'objchttp_Tests' do
    inherit! :search_paths

  end

  target 'objchttp_Example_Swift' do
    pod 'objchttp', :path => '../'
    
    end
end
